### ISSUE TITLE
Packages with a git url as the version does not work

### ISSUE THREAD

**Issue by smitt04** [appcelerator/npm-fast-install#4]
We have some private repos that we install from git url, when your script hits them it chokes with 

```
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received null
    at assertPath (path.js:7:11)
    at Object.join (path.js:1227:7)
    at /usr/local/lib/node_modules/npm-fast-install/index.js:136:32
    at /usr/local/lib/node_modules/npm-fast-install/node_modules/npm/lib/view.js:144:28
    at CachingRegistryClient.get_ (/usr/local/lib/node_modules/npm-fast-install/node_modules/npm/lib/cache/caching-client.js:125:16)
    at /usr/local/lib/node_modules/npm-fast-install/node_modules/npm/lib/cache/caching-client.js:91:14
    at /usr/local/lib/node_modules/npm-fast-install/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

it is because `ver` is null when trying to create cache dir, even if you fix that issue by just passing `dep.ver` if it can not resolve version, later down the script can not install packages from git urls.

**Comment by atplack-tribridge** [comment]
lodash@2.4.1 also now has this problem because of graceful-fs using map-stream.
